export const mongodb = 'mongodb://ndit.pwnt.co';
export const regions = ['br', 'eune', 'euw', 'kr', 'lan', 'las', 'na', 'oce', 'ru', 'tr'];
export const tiers = ['challenger', 'master'];
export const apikey = '5f1c0c7d-d474-4b79-8480-a53c9c41ad60';
export const region = 'na';
export const limitPer10s = 10;
export const limitPer10min = 500;
export const cacheTTL = 3600;
export const endpoint = 'api.pvp.net/api/lol';